export const emojidata = [
    {
        title:":tomato:",
        img:"/images/image5.png"
    },
     {
        title:":smile-1:",
        img:"/images/image1.png"
    },
     {
        title:":x0x:",
        img:"/images/image3.png"
    },
     {
        title:":smile-3:",
        img:"/images/image3.png"
    },
     {
        title:":anxious:",
        img:"/images/image4.png"
    },
     {
        title:":confused:",
        img:"/images/image6.png"
    },
     {
        title:":smile-2:",
        img:"/images/image1.png"
    },
     {
        title:":smile-2:",
        img:"/images/image1.png"
    },
    {
        title:":confused:",
        img:"/images/image6.png"
    },
    {
        title:":sunglasses:",
        img:"/images/image2.png"
    },
    {
        title:":smile-1:",
        img:"/images/image1.png"
    },
    {
        title:":smile-1:",
        img:"/images/image.png"
    },
    {
        title:":x0x:",
        img:"/images/image3.png"
    },
     {
        title:":sunglasses:",
        img:"/images/image2.png"
    },
    {
        title:":tomato:",
        img:"/images/image5.png"
    },
    {
        title:":family:",
        img:"/images/image7.png"
    },
]

export const imagefamily={
        title:":family:",
        img:"/images/image7.png"
}